#!/usr/bin/env bash
#local host to resolve to 127.0.0.2 and facebook.com to resolve to 0.0.0.0

cp /etc/hosts ~/hosts.new
sed -i s/^127.*localhost$/127.0.0.2\ localhost/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
